### ISSUE TITLE
Feature Request: Add filter settings and support for php require

### ISSUE THREAD

**Issue by yCodeTech** [rioj7/html-related-links#1]
Feature request 1: I work with lots of anchor links in my pages, but the extension displays these in the view. I don't believe this should be the intended feature, and the same goes for `tel:` and `mailto:` links. The addition of some settings to filter out what we don't want to be in the view would be good. 

Feature request 2: It would also be good to add support for files linked via both the php require functions.

**Comment by rioj7** [comment]
v0.1.2 anchor links and protocols (mailto:,...) are fixed

**Comment by rioj7** [comment]
v0.2.0 adds include and exclude configuration

**Comment by rioj7** [comment]
Fixed in commit d8cafa0 (v0.1.2) and 12791dc (v0.2.0)
