### ISSUE TITLE
File link can't parse space

### ISSUE THREAD

**Issue by chenweifelix** [rioj7/html-related-links#11]
I was wondering if it would be possible to make the file link able to parse space?

**Comment by rioj7** [comment]
@chenweifelix  With regex you can parse almost anything. Can you given an example of what you want to parse.

**Comment by chenweifelix** [comment]
Hi, thanks for your reply. 

I am able to detect the path using regex; however, it seems that I can't open the file if there's a space in the folder. For instance, I can open the file in this path: `Users/user/Desktop/file.py` but not this one `Users/user/Desktop/folder 1/file.py`

**Comment by rioj7** [comment]
@chenweifelix 

I tried with setting:

```json
      { "find": "#\\s\\{@link ([^}]+)\\}",
        "filePath": "$1"
      }
```

on file with content:

```none
# {@link folder 1/file.py}
```

on a Windows system and had no problem opening the file `folder 1/file.py` by:

* using `Ctrl+Click` in the document
* Clicking in the **Related Links** View
