### ISSUE TITLE
Feature: Open files from Editor via Alt+Click

### ISSUE THREAD

**Issue by grefel** [rioj7/html-related-links#5]
Would be great to open the additonal file links in the editor window via Alt + Mouse Click. As far as I can see I can only open the files via the View.

**Comment by grefel** [comment]
I just hacked this extendsion https://github.com/grefel/vscode-jump-to-file for my needs, based on https://github.com/ctf0/vscode-jump-to-line-number

**Comment by rioj7** [comment]
@grefel I have added a `DocumentLinkProvider`
