### ISSUE TITLE
Opening related file with find and replace

### ISSUE THREAD

**Issue by oriolgual** [rioj7/html-related-links#7]
I've been trying to setup a keybinding to open the spec file of a Ruby file. Following an example that I found on Stackoverflow I created the keybinding with:

```json
     {
        "key": "ctrl+shift+t",
        "command": "htmlRelatedLinks.openFile",
        "args": {
            "file": "${workspaceFolder:Backend}/${relativeFileDirname:find=^app$:replace=spec}/${fileBasenameNoExtension}_spec.rb",
            "method": "vscode.open",
            "viewColumn": "split"
        },
        "when": "editorTextFocus && editorLangId == ruby"
    }
```

But it seems that the transformation is not working for `relativeFileDirname` since it tries to open a dir with the regex as the name. 

I've tried debugging the extension, and what I've found is that the generated regex `\$\{relativeFileDirname(\}|([^a-zA-Z{}$]+)([\s\S]+?)\2\})` does not match the variable `data` at `transformVariable`, being data `/path/to/backend/${relativeFileDirname:find=^app$:replace=spec}/my_class_spec.rb'`

Any ideas how to fix this?

**Comment by rioj7** [comment]
@oriolgual 

> `${variableName separator properties separator}`

Your separator is `:` and you are missing the one needed at the end

**Comment by oriolgual** [comment]
Thanks for the quick response! Yes, I have subdirs. My goal was to change `path/to/backend/app/dir1/dir2/dirn/file.rb` to `path/to/backend/spec/dir1/dir2/dirn/file.rb`

**Comment by oriolgual** [comment]
Working now! The correct config was:

     {
        "key": "ctrl+shift+t",
        "command": "htmlRelatedLinks.openFile",
        "args": {
            "file": "${workspaceFolder:Backend}/${relativeFileDirname:find=app:replace=spec:}/${fileBasenameNoExtension}_spec.rb",
            "method": "vscode.open",
            "viewColumn": "split"
        },
        "when": "editorTextFocus && editorLangId == ruby"
    }

**Comment by oriolgual** [comment]
Would it be possible to also show this (the spec from a ruby file) at the HTML links view?

**Comment by rioj7** [comment]
@oriolgual  Better is to use `${relativeFileDirname:find=/app/:replace=/spec/:}`

**Comment by rioj7** [comment]
@oriolgual 

I think the following setting will work

```json
  "html-related-links.include": {
    "ruby": [
      {
        "find": "^",
        "filePath": "${workspaceFolder:Backend}/${relativeFileDirname:find=app:replace=spec:}/${fileBasenameNoExtension}_spec.rb"
      }
    ]
  },
  "html-related-links.exclude": [
    "_spec_spec.rb"
  ]
```

* If start of the file is found (`^`) create the spec file.
* Do not allow a spec file of the spec file

**Comment by oriolgual** [comment]
Thanks for the help!

**Comment by rioj7** [comment]
@oriolgual 

I wanted to add this as an example to the README but discovered a few problems:

* `find` has to capture at least 1 character
* if you want to handle different directory separators and `app` being the end of the relative path you have to be a bit regex creative.
* modify `replace` so it uses the capture groups of the transform `find`

```json
  "html-related-links.include": {
    "ruby": [
      {
        "find": "^(.)",
        "filePath": "${workspaceFolder:Backend}/${relativeFileDirname:find=([\\\\/])app(\\1|$):replace=$$1spec$$2:}/${fileBasenameNoExtension}_spec.rb"
      }
    ]
  },
  "html-related-links.exclude": [
    "_spec_spec.rb"
  ]
```
