### ISSUE TITLE
php

### ISSUE THREAD

**Issue by guttenplanfd** [rioj7/html-related-links#9]
Most of my files are .php not .HTML how can I get this to work with those file types?

**Comment by guttenplanfd** [comment]
This is what my settings.json looks like, but nothing is showing in the related links for any file with .PHP (index.php)
`{
    "ediSupport.inlayHints.segmentNames": false,
    "ediSupport.inlayHints.elements": false,
    "git.ignoreMissingGitWarning": true,
    "html-related-links.alwaysShow": true,
    "html-related-links.include": {
    

      "php": [
        "(?:require|include)(?:_once)?\\('([^']+)'\\)",
        "(?:require|include)(?:_once)? '([^']+)'",
        "(?:require|include)(?:_once)?\\(\"([^\"]+)\"\\)",
        "(?:require|include)(?:_once)? \"([^\"]+)\"",
        "<(?:a|img|link|script)[^>]*? (?:src|href)=['\"]((?!//|[^:>'\"]*:)[^#?>'\"]*)(?:[^>'\"]*)['\"][^>]*>"
      ]
    }
}`

**Comment by guttenplanfd** [comment]
Nevermind I just realized I did not add it to the workspace, all good now

**Comment by rioj7** [comment]
@guttenplanfd
Which `settings,json` did you modified first?
It should work with the Global/User `settings,json`
